#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="sophiavpn"
APP_NAME="SophiaVPN"
OS="$(uname -s)"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/$APP_ID"
CLI="$BIN_DIR/sophia"
COMPAT_CLI="$BIN_DIR/svpn"
SHELL_HOOK_FILE="$HOME/.config/SophiaVPN/shell-hook.sh"

cd "$ROOT_DIR"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required. Install Node.js 18+ first." >&2
  exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required. Install npm first." >&2
  exit 1
fi

bash "$ROOT_DIR/scripts/install-electron.sh"

echo "Installing mihomo core"
"$ROOT_DIR/scripts/install-core.sh"
chmod 0755 \
  "$ROOT_DIR/bin/sophia" \
  "$ROOT_DIR/bin/svpn" \
  "$ROOT_DIR/scripts/core-watchdog.sh" \
  "$ROOT_DIR/scripts/install-electron.sh" \
  "$ROOT_DIR/scripts/install-core.sh" \
  "$ROOT_DIR/scripts/install-sophia.sh" \
  "$ROOT_DIR/scripts/install-svpn.sh" \
  "$ROOT_DIR/scripts/macos-system-proxy.sh" \
  "$ROOT_DIR/scripts/macos-conflict-check.sh" \
  "$ROOT_DIR/scripts/install-tun.sh" 2>/dev/null || true

mkdir -p "$BIN_DIR" "$(dirname "$SHELL_HOOK_FILE")"

if [[ "$OS" == "Darwin" ]]; then
  ELECTRON_BINARY="$ROOT_DIR/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
else
  ELECTRON_BINARY="$ROOT_DIR/node_modules/electron/dist/electron"
fi

if [[ ! -x "$ELECTRON_BINARY" ]]; then
  echo "Electron runtime was not installed correctly: $ELECTRON_BINARY" >&2
  exit 1
fi

if [[ ! -f "$ROOT_DIR/renderer/static/media/silvervpn.png" && -f "$ROOT_DIR/renderer/static/media/silvervpn.png.base64" ]]; then
  if base64 --help 2>&1 | grep -q -- '--decode'; then
    base64 --decode "$ROOT_DIR/renderer/static/media/silvervpn.png.base64" > "$ROOT_DIR/renderer/static/media/silvervpn.png"
  else
    base64 -D -i "$ROOT_DIR/renderer/static/media/silvervpn.png.base64" -o "$ROOT_DIR/renderer/static/media/silvervpn.png"
  fi
fi

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$ROOT_DIR"
OS="\$(uname -s)"
if [[ "\$OS" == "Darwin" ]]; then
  ELECTRON="\$APP_DIR/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
  STATE_DIR="\${HOME}/Library/Logs/SophiaVPN"
else
  ELECTRON="\$APP_DIR/node_modules/electron/dist/electron"
  STATE_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/SophiaVPN"
fi
LOG_FILE="\$STATE_DIR/launcher.log"
mkdir -p "\$STATE_DIR"
exec >>"\$LOG_FILE" 2>&1
printf '\n[%s] Starting SophiaVPN\n' "\$(date -Iseconds 2>/dev/null || date)"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\${PATH:-}"
export SOPHIAVPN_DATA_DIR="\${SOPHIAVPN_DATA_DIR:-\$HOME/.config/SophiaVPN}"
export SILVERVPN_DATA_DIR="\$SOPHIAVPN_DATA_DIR"
cd "\$APP_DIR"
if [[ ! -x "\$ELECTRON" ]]; then
  echo "Electron runtime is missing: \$ELECTRON"
  exit 1
fi
if [[ "\$OS" == "Darwin" ]]; then
  exec "\$ELECTRON" "\$APP_DIR"
else
  exec "\$ELECTRON" --no-sandbox "\$APP_DIR"
fi
EOF
chmod +x "$WRAPPER"
ln -sfn "$ROOT_DIR/bin/sophia" "$CLI"
ln -sfn "$ROOT_DIR/bin/svpn" "$COMPAT_CLI"

cat > "$SHELL_HOOK_FILE" <<'EOF'
# Generated by SophiaVPN. This file is safe to source from Bash and Zsh.
sophia_sync_proxy_env() {
  local state_file="$HOME/.config/SophiaVPN/shell-proxy.sh"
  if [[ -r "$state_file" ]]; then
    # shellcheck disable=SC1090
    source "$state_file"
  fi
}

if [[ -n "${BASH_VERSION:-}" ]]; then
  case ";${PROMPT_COMMAND:-};" in
    *";sophia_sync_proxy_env;"*) ;;
    *) PROMPT_COMMAND="sophia_sync_proxy_env${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  if type add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd sophia_sync_proxy_env
  fi
fi

sophia_sync_proxy_env
EOF
chmod 0600 "$SHELL_HOOK_FILE"

install_shell_hook() {
  local shell_rc="$1"
  local source_line='[[ -r "$HOME/.config/SophiaVPN/shell-hook.sh" ]] && source "$HOME/.config/SophiaVPN/shell-hook.sh"'
  touch "$shell_rc"
  if ! grep -Fq '.config/SophiaVPN/shell-hook.sh' "$shell_rc"; then
    {
      printf '\n# SophiaVPN terminal proxy integration\n'
      printf '%s\n' "$source_line"
    } >> "$shell_rc"
  fi
}

install_shell_hook "$HOME/.bashrc"
if [[ -f "$HOME/.zshrc" ]] || [[ "${SHELL:-}" == */zsh ]] || [[ "$OS" == "Darwin" ]]; then
  install_shell_hook "$HOME/.zshrc"
fi

if [[ "$OS" == "Darwin" ]]; then
  APP_BUNDLE="$HOME/Applications/SophiaVPN.app"
  mkdir -p "$APP_BUNDLE/Contents/MacOS" "$APP_BUNDLE/Contents/Resources"
  cat > "$APP_BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>SophiaVPN</string>
  <key>CFBundleDisplayName</key><string>SophiaVPN</string>
  <key>CFBundleIdentifier</key><string>com.sophia.vpn</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundleExecutable</key><string>SophiaVPN</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
  cat > "$APP_BUNDLE/Contents/MacOS/SophiaVPN" <<EOF
#!/usr/bin/env bash
exec "$WRAPPER"
EOF
  chmod +x "$APP_BUNDLE/Contents/MacOS/SophiaVPN"
  echo "Installed $APP_NAME for macOS"
  echo "Launch app: open \"$APP_BUNDLE\""
  echo "Launch command: $WRAPPER"
  echo "CLI command: $CLI"
  echo "Launcher log: $HOME/Library/Logs/SophiaVPN/launcher.log"
  echo "Note: TUN mode is not enabled; SophiaVPN uses proxy-only mode by default."
  echo "Conflict check: sophia conflicts"
  exit 0
fi

echo "Installed $APP_NAME"
echo "Launch from the application menu or run: $WRAPPER"
echo "CLI command: $CLI"
echo "Desktop launcher log: ${XDG_STATE_HOME:-$HOME/.local/state}/SophiaVPN/launcher.log"
