#!/usr/bin/env bash
set -euo pipefail

APP_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR="$HOME/.local/bin"
TARGET="$TARGET_DIR/svpn"
CONFIG_DIR="$HOME/.config/SilverVPN"
HOOK_FILE="$CONFIG_DIR/shell-hook.sh"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required." >&2
  exit 1
fi
if ! node -e "require('$APP_ROOT/node_modules/js-yaml')" >/dev/null 2>&1; then
  echo "js-yaml is missing. Run npm install in $APP_ROOT first." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR" "$CONFIG_DIR"
chmod 0755 "$APP_ROOT/bin/svpn.js" "$APP_ROOT/bin/svpn"
[ -f "$APP_ROOT/bin/svpn-import.js" ] && chmod 0755 "$APP_ROOT/bin/svpn-import.js"
[ -f "$APP_ROOT/bin/svpn-profile.js" ] && chmod 0755 "$APP_ROOT/bin/svpn-profile.js"
[ -f "$APP_ROOT/scripts/macos-system-proxy.sh" ] && chmod 0755 "$APP_ROOT/scripts/macos-system-proxy.sh"
ln -sfn "$APP_ROOT/bin/svpn" "$TARGET"

cat > "$HOOK_FILE" <<'EOF'
# Generated by SilverVPN. Safe for Bash and Zsh.
svpn_sync_proxy_env() {
  local state_file="$HOME/.config/SilverVPN/shell-proxy.sh"
  if [ -r "$state_file" ]; then
    # shellcheck disable=SC1090
    . "$state_file"
  fi
}

if [ -n "${BASH_VERSION:-}" ]; then
  case ";${PROMPT_COMMAND:-};" in
    *";svpn_sync_proxy_env;"*) ;;
    *) PROMPT_COMMAND="svpn_sync_proxy_env${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
elif [ -n "${ZSH_VERSION:-}" ]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  if type add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd svpn_sync_proxy_env
  fi
fi

svpn_sync_proxy_env
EOF
chmod 0600 "$HOOK_FILE"

install_rc_lines() {
  local file="$1"
  touch "$file"
  if ! grep -Fq 'export PATH="$HOME/.local/bin:$PATH"' "$file"; then
    printf '\n# SilverVPN user commands\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$file"
  fi
  if ! grep -Fq '.config/SilverVPN/shell-hook.sh' "$file"; then
    printf 'if [ -r "$HOME/.config/SilverVPN/shell-hook.sh" ]; then . "$HOME/.config/SilverVPN/shell-hook.sh"; fi\n' >> "$file"
  fi
}

install_rc_lines "$HOME/.bashrc"
install_rc_lines "$HOME/.profile"
if [ -f "$HOME/.zshrc" ] || [ "$(uname -s)" = "Darwin" ] || [ "${SHELL:-}" = "$(command -v zsh 2>/dev/null || true)" ]; then
  install_rc_lines "$HOME/.zshrc"
fi

cat <<EOF
SilverVPN svpn command installed:
  $TARGET

Open a new shell, then use:
  svpn import '<subscription-url-or-file>' 'My Profile'
  svpn on
  svpn status
  svpn test

Optional personal port configuration:
  svpn config ports <base-port>

macOS system proxy helper:
  svpn system-proxy on|off|status

The shell hook automatically synchronizes terminal proxy state.
Proxy-only mode does not use TUN, sudo, /etc edits, routes, DNS or global shell proxy settings.
EOF
