#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="sophiavpn"
APP_NAME="SophiaVPN"
OS="$(uname -s)"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/$APP_ID"
CLI="$BIN_DIR/sophia"
COMPAT_CLI="$BIN_DIR/svpn"
SHELL_HOOK_FILE="$HOME/.config/SophiaVPN/shell-hook.sh"

cd "$ROOT_DIR"

bash "$ROOT_DIR/scripts/install-node-runtime.sh"
NODE_BIN="$ROOT_DIR/resources/node-runtime/bin/node"
NPM_BIN="$ROOT_DIR/resources/node-runtime/bin/npm"
export SOPHIA_NODE="$NODE_BIN"
export SOPHIA_NPM="$NPM_BIN"

bash "$ROOT_DIR/scripts/install-electron.sh"

echo "Installing mihomo core"
"$ROOT_DIR/scripts/install-core.sh"
chmod 0755 \
  "$ROOT_DIR/bin/sophia" \
  "$ROOT_DIR/bin/svpn" \
  "$ROOT_DIR/scripts/core-watchdog.sh" \
  "$ROOT_DIR/scripts/install-electron.sh" \
  "$ROOT_DIR/scripts/install-node-runtime.sh" \
  "$ROOT_DIR/scripts/install-core.sh" \
  "$ROOT_DIR/scripts/install-sophia.sh" \
  "$ROOT_DIR/scripts/install-svpn.sh" \
  "$ROOT_DIR/scripts/macos-system-proxy.sh" \
  "$ROOT_DIR/scripts/macos-conflict-check.sh" \
  "$ROOT_DIR/scripts/install-tun.sh" 2>/dev/null || true

mkdir -p "$BIN_DIR" "$(dirname "$SHELL_HOOK_FILE")"

if [[ "$OS" == "Darwin" ]]; then
  ELECTRON_BINARY="$ROOT_DIR/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
else
  ELECTRON_BINARY="$ROOT_DIR/node_modules/electron/dist/electron"
fi

if [[ ! -x "$ELECTRON_BINARY" ]]; then
  echo "Electron runtime was not installed correctly: $ELECTRON_BINARY" >&2
  exit 1
fi

ICON_PNG="$ROOT_DIR/resources/SophiaVPN-icon.png"
LEGACY_ICON_PNG="$ROOT_DIR/renderer/static/media/silvervpn.png"
ICON_BASE64="$ROOT_DIR/renderer/static/media/silvervpn.png.base64"
ICON_ICNS="$ROOT_DIR/resources/SophiaVPN.icns"

if [[ ! -s "$ICON_PNG" && -s "$LEGACY_ICON_PNG" ]]; then
  cp "$LEGACY_ICON_PNG" "$ICON_PNG"
fi

if [[ ! -s "$ICON_PNG" && -f "$ICON_BASE64" ]]; then
  ICON_TMP="$(mktemp)"
  if base64 --decode < "$ICON_BASE64" > "$ICON_TMP" 2>/dev/null ||
    base64 -D -i "$ICON_BASE64" -o "$ICON_TMP"; then
    mv "$ICON_TMP" "$ICON_PNG"
  else
    rm -f "$ICON_TMP"
    echo "Failed to decode SophiaVPN icon asset." >&2
    exit 1
  fi
fi

if [[ -s "$ICON_PNG" ]]; then
  cp "$ICON_PNG" "$LEGACY_ICON_PNG"
fi

if [[ "$OS" == "Darwin" && -s "$ICON_PNG" ]] && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
  ICON_WORK="$(mktemp -d)"
  ICONSET="$ICON_WORK/SophiaVPN.iconset"
  mkdir -p "$ICONSET"
  sips -z 16 16 "$ICON_PNG" --out "$ICONSET/icon_16x16.png" >/dev/null
  sips -z 32 32 "$ICON_PNG" --out "$ICONSET/icon_16x16@2x.png" >/dev/null
  sips -z 32 32 "$ICON_PNG" --out "$ICONSET/icon_32x32.png" >/dev/null
  sips -z 64 64 "$ICON_PNG" --out "$ICONSET/icon_32x32@2x.png" >/dev/null
  sips -z 128 128 "$ICON_PNG" --out "$ICONSET/icon_128x128.png" >/dev/null
  sips -z 256 256 "$ICON_PNG" --out "$ICONSET/icon_128x128@2x.png" >/dev/null
  sips -z 256 256 "$ICON_PNG" --out "$ICONSET/icon_256x256.png" >/dev/null
  sips -z 512 512 "$ICON_PNG" --out "$ICONSET/icon_256x256@2x.png" >/dev/null
  sips -z 512 512 "$ICON_PNG" --out "$ICONSET/icon_512x512.png" >/dev/null
  sips -z 1024 1024 "$ICON_PNG" --out "$ICONSET/icon_512x512@2x.png" >/dev/null
  iconutil -c icns "$ICONSET" -o "$ICON_ICNS"
  rm -rf "$ICON_WORK"
fi

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$ROOT_DIR"
OS="\$(uname -s)"
if [[ "\$OS" == "Darwin" ]]; then
  ELECTRON="\$APP_DIR/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
  STATE_DIR="\${HOME}/Library/Logs/SophiaVPN"
else
  ELECTRON="\$APP_DIR/node_modules/electron/dist/electron"
  STATE_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/SophiaVPN"
fi
LOG_FILE="\$STATE_DIR/launcher.log"
mkdir -p "\$STATE_DIR"
exec >>"\$LOG_FILE" 2>&1
printf '\n[%s] Starting SophiaVPN\n' "\$(date -Iseconds 2>/dev/null || date)"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\${PATH:-}"
export SOPHIA_NODE="$NODE_BIN"
export SOPHIAVPN_DATA_DIR="\${SOPHIAVPN_DATA_DIR:-\$HOME/.config/SophiaVPN}"
export SILVERVPN_DATA_DIR="\$SOPHIAVPN_DATA_DIR"
cd "\$APP_DIR"
if [[ ! -x "\$ELECTRON" ]]; then
  echo "Electron runtime is missing: \$ELECTRON"
  exit 1
fi
if [[ "\$OS" == "Darwin" ]]; then
  exec "\$ELECTRON" "\$APP_DIR"
else
  exec "\$ELECTRON" --no-sandbox "\$APP_DIR"
fi
EOF
chmod +x "$WRAPPER"

rm -f "$CLI" "$COMPAT_CLI"

cat > "$CLI" <<EOF
#!/usr/bin/env bash
export SOPHIA_NODE="$NODE_BIN"
exec "$ROOT_DIR/bin/sophia" "\$@"
EOF
chmod 0755 "$CLI"

cat > "$COMPAT_CLI" <<EOF
#!/usr/bin/env bash
export SOPHIA_NODE="$NODE_BIN"
exec "$ROOT_DIR/bin/svpn" "\$@"
EOF
chmod 0755 "$COMPAT_CLI"

cat > "$SHELL_HOOK_FILE" <<'EOF'
# Generated by SophiaVPN. This file is safe to source from Bash and Zsh.
sophia_sync_proxy_env() {
  local state_file="$HOME/.config/SophiaVPN/shell-proxy.sh"
  if [[ -r "$state_file" ]]; then
    # shellcheck disable=SC1090
    source "$state_file"
  fi
}

if [[ -n "${BASH_VERSION:-}" ]]; then
  case ";${PROMPT_COMMAND:-};" in
    *";sophia_sync_proxy_env;"*) ;;
    *) PROMPT_COMMAND="sophia_sync_proxy_env${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  if type add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd sophia_sync_proxy_env
  fi
fi

sophia_sync_proxy_env
EOF
chmod 0600 "$SHELL_HOOK_FILE"

install_shell_hook() {
  local shell_rc="$1"
  local source_line='[[ -r "$HOME/.config/SophiaVPN/shell-hook.sh" ]] && source "$HOME/.config/SophiaVPN/shell-hook.sh"'
  touch "$shell_rc"
  if ! grep -Fq '.config/SophiaVPN/shell-hook.sh' "$shell_rc"; then
    {
      printf '\n# SophiaVPN terminal proxy integration\n'
      printf '%s\n' "$source_line"
    } >> "$shell_rc"
  fi
}

install_shell_hook "$HOME/.bashrc"
if [[ -f "$HOME/.zshrc" ]] || [[ "${SHELL:-}" == */zsh ]] || [[ "$OS" == "Darwin" ]]; then
  install_shell_hook "$HOME/.zshrc"
fi

if [[ "$OS" == "Darwin" ]]; then
  APP_BUNDLE="$HOME/Applications/SophiaVPN.app"
  mkdir -p "$APP_BUNDLE/Contents/MacOS" "$APP_BUNDLE/Contents/Resources"
  cat > "$APP_BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>SophiaVPN</string>
  <key>CFBundleDisplayName</key><string>SophiaVPN</string>
  <key>CFBundleIdentifier</key><string>com.sophia.vpn</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundleExecutable</key><string>SophiaVPN</string>
  <key>CFBundleIconFile</key><string>SophiaVPN</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
  if [[ -s "$ICON_ICNS" ]]; then
    cp "$ICON_ICNS" "$APP_BUNDLE/Contents/Resources/SophiaVPN.icns"
  fi
  cat > "$APP_BUNDLE/Contents/MacOS/SophiaVPN" <<EOF
#!/usr/bin/env bash
exec "$WRAPPER"
EOF
  chmod +x "$APP_BUNDLE/Contents/MacOS/SophiaVPN"
  touch "$APP_BUNDLE"
  echo "Installed $APP_NAME for macOS"
  echo "Launch app: open \"$APP_BUNDLE\""
  echo "Launch command: $WRAPPER"
  echo "CLI command: $CLI"
  echo "Launcher log: $HOME/Library/Logs/SophiaVPN/launcher.log"
  echo "Note: TUN mode is not enabled; SophiaVPN uses proxy-only mode by default."
  echo "Conflict check: sophia conflicts"
  exit 0
fi

echo "Installed $APP_NAME"
echo "Launch from the application menu or run: $WRAPPER"
echo "CLI command: $CLI"
echo "Desktop launcher log: ${XDG_STATE_HOME:-$HOME/.local/state}/SophiaVPN/launcher.log"
