#!/usr/bin/env bash
set -euo pipefail

APP_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR="$HOME/.local/bin"
TARGET="$TARGET_DIR/sophia"
COMPAT_TARGET="$TARGET_DIR/svpn"
CONFIG_DIR="$HOME/.config/SophiaVPN"
HOOK_FILE="$CONFIG_DIR/shell-hook.sh"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required." >&2
  exit 1
fi
if ! node -e "require('$APP_ROOT/node_modules/js-yaml')" >/dev/null 2>&1; then
  echo "js-yaml is missing. Run npm install in $APP_ROOT first." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR" "$CONFIG_DIR"
chmod 0755 "$APP_ROOT/bin/sophia" "$APP_ROOT/bin/svpn" "$APP_ROOT/bin/svpn.js" 2>/dev/null || true
[ -f "$APP_ROOT/bin/svpn-import.js" ] && chmod 0755 "$APP_ROOT/bin/svpn-import.js"
[ -f "$APP_ROOT/bin/svpn-profile.js" ] && chmod 0755 "$APP_ROOT/bin/svpn-profile.js"
[ -f "$APP_ROOT/scripts/macos-system-proxy.sh" ] && chmod 0755 "$APP_ROOT/scripts/macos-system-proxy.sh"
[ -f "$APP_ROOT/scripts/macos-conflict-check.sh" ] && chmod 0755 "$APP_ROOT/scripts/macos-conflict-check.sh"
ln -sfn "$APP_ROOT/bin/sophia" "$TARGET"
ln -sfn "$APP_ROOT/bin/svpn" "$COMPAT_TARGET"

cat > "$HOOK_FILE" <<'EOF'
# Generated by SophiaVPN. Safe for Bash and Zsh.
sophia_sync_proxy_env() {
  local state_file="$HOME/.config/SophiaVPN/shell-proxy.sh"
  if [ -r "$state_file" ]; then
    # shellcheck disable=SC1090
    . "$state_file"
  fi
}

if [ -n "${BASH_VERSION:-}" ]; then
  case ";${PROMPT_COMMAND:-};" in
    *";sophia_sync_proxy_env;"*) ;;
    *) PROMPT_COMMAND="sophia_sync_proxy_env${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
elif [ -n "${ZSH_VERSION:-}" ]; then
  autoload -Uz add-zsh-hook 2>/dev/null || true
  if type add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd sophia_sync_proxy_env
  fi
fi

sophia_sync_proxy_env
EOF
chmod 0600 "$HOOK_FILE"

install_rc_lines() {
  local file="$1"
  touch "$file"
  if ! grep -Fq 'export PATH="$HOME/.local/bin:$PATH"' "$file"; then
    printf '\n# SophiaVPN user commands\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$file"
  fi
  if ! grep -Fq '.config/SophiaVPN/shell-hook.sh' "$file"; then
    printf 'if [ -r "$HOME/.config/SophiaVPN/shell-hook.sh" ]; then . "$HOME/.config/SophiaVPN/shell-hook.sh"; fi\n' >> "$file"
  fi
}

install_rc_lines "$HOME/.bashrc"
install_rc_lines "$HOME/.profile"
if [ -f "$HOME/.zshrc" ] || [ "$(uname -s)" = "Darwin" ] || [ "${SHELL:-}" = "$(command -v zsh 2>/dev/null || true)" ]; then
  install_rc_lines "$HOME/.zshrc"
fi

cat <<EOF
SophiaVPN command installed:
  $TARGET

Compatibility alias installed:
  $COMPAT_TARGET

Open a new shell, then use:
  sophia import '<subscription-url-or-file>' 'My Profile'
  sophia conflicts
  sophia on
  sophia status
  sophia test

Optional personal port configuration:
  sophia config ports <base-port>

macOS system proxy helper:
  sophia system-proxy on|off|status

The shell hook automatically synchronizes terminal proxy state.
SophiaVPN uses ~/.config/SophiaVPN and avoids automatic macOS system-proxy takeover when other VPN/proxy/network-access clients are detected.
EOF
